name: Run Python Script

on:
  schedule:
    - cron: '0 */2 * * *'  # Запуск каждые 2 часа
  workflow_dispatch:  # Позволяет запускать workflow вручную из интерфейса GitHub

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Укажите нужную версию Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz

    - name: Run the script
      run: |
        python send_transaction.py  # Замените на имя вашего скрипта
